### ISSUE TITLE
init.php

### ISSUE THREAD

**Issue by sergeyklay** [WinterSilence/log-reader#1]
Убери эту фигню с проверкой продакшена, перенеси её в конфиг

**Comment by WinterSilence** [comment]
модуль вообще сырой, если бы mad_b не заикнулся я бы даже выкладывать не стал пока. сам по себе он мне не скоро понадобится т.ч. как дойдут руки доделаю по полнофункциональной версии

**Comment by sergeyklay** [comment]
ok
